[project]
name = "joke-api"
version = "0.1.0"
description = "Jokes API"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.129.0",
    "httpx>=0.28.1",
    "uvicorn>=0.41.0",
]
